// Package corpus walks source trees and yields clean, deduped source files
// for model training. It prefers `git ls-files` so .gitignore is respected
// and only tracked files are indexed; it falls back to a filesystem walk.
package corpus

import (
	"bytes"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

var skipDirs = map[string]bool{
	".git": true, ".hg": true, ".svn": true,
	"node_modules": true, "vendor": true, "dist": true,
	"build": true, "out": true, "target": true, "bin": true,
	"__pycache__": true, ".venv": true, "venv": true,
	".next": true, ".nuxt": true, ".cache": true,
	".idea": true, ".vscode": true, "coverage": true,
	"testdata": true, "third_party": true, "external": true,
}

var skipExt = map[string]bool{
	".min.js": true, ".lock": true, ".sum": true,
	".png": true, ".jpg": true, ".jpeg": true, ".gif": true,
	".ico": true, ".woff": true, ".woff2": true, ".ttf": true,
	".zip": true, ".tar": true, ".gz": true, ".xz": true,
	".pdf": true, ".so": true, ".dll": true, ".exe": true,
	".bin": true, ".wasm": true, ".map": true, ".snap": true,
	".pb.go": true, ".generated.go": true, ".g.dart": true,
	".svg": true, ".mp3": true, ".mp4": true, ".webm": true,
	".webp": true, ".jar": true, ".class": true, ".o": true,
}

var generatedMarkers = [][]byte{
	[]byte("DO NOT EDIT"),
	[]byte("auto-generated"),
	[]byte("autogenerated"),
	[]byte("Auto-generated"),
	[]byte("Automatically generated"),
	[]byte("@generated"),
}

const (
	maxFileSize = 1 << 20 // 1 MiB
	maxLineLen  = 500     // minified lines
)

// File is one source file from the corpus.
type File struct {
	Path string
	Repo string // top-level directory name that contained it
	Data []byte
}

func looksBinary(data []byte) bool {
	n := len(data)
	if n > 8192 {
		n = 8192
	}
	return bytes.IndexByte(data[:n], 0) >= 0
}

func isGenerated(data []byte) bool {
	n := len(data)
	if n > 4096 {
		n = 4096
	}
	head := data[:n]
	for _, m := range generatedMarkers {
		if bytes.Contains(head, m) {
			return true
		}
	}
	return false
}

func hasLongLines(data []byte) bool {
	// Sample: any line > maxLineLen marks the file as minified/dumped.
	start := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '\n' {
			if i-start > maxLineLen {
				return true
			}
			start = i + 1
			if start > 1<<20 {
				break
			}
		}
	}
	return false
}

func accept(path string, data []byte) bool {
	ext := strings.ToLower(filepath.Ext(path))
	if skipExt[ext] {
		return false
	}
	// Double extensions like .min.js
	name := strings.ToLower(filepath.Base(path))
	for suf := range skipExt {
		if strings.HasSuffix(name, suf) {
			return false
		}
	}
	if len(data) == 0 || len(data) > maxFileSize {
		return false
	}
	if looksBinary(data) || isGenerated(data) {
		return false
	}
	if hasLongLines(data) {
		return false
	}
	return true
}

func gitFiles(root string) ([]string, bool) {
	cmd := exec.Command("git", "-C", root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
	out, err := cmd.Output()
	if err != nil {
		return nil, false
	}
	parts := strings.Split(string(out), "\x00")
	rel := parts[:0]
	for _, p := range parts {
		if p != "" {
			rel = append(rel, p)
		}
	}
	return rel, true
}

func walkFiles(root string) []string {
	var rel []string
	filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if path != root && skipDirs[d.Name()] {
				return fs.SkipDir
			}
			if path != root && strings.HasPrefix(d.Name(), ".") {
				return fs.SkipDir
			}
			return nil
		}
		r, err := filepath.Rel(root, path)
		if err == nil {
			rel = append(rel, r)
		}
		return nil
	})
	return rel
}

// Collect gathers acceptable files under each root. Each root may be a
// single repo or a directory containing repos.
func Collect(roots []string, out chan<- File) error {
	defer close(out)
	for _, root := range roots {
		root, err := filepath.Abs(root)
		if err != nil {
			continue
		}
		info, err := os.Stat(root)
		if err != nil || !info.IsDir() {
			continue
		}
		repoName := filepath.Base(root)
		var rels []string
		if r, ok := gitFiles(root); ok {
			rels = r
		} else {
			rels = walkFiles(root)
		}
		sort.Strings(rels)
		for _, rel := range rels {
			full := filepath.Join(root, rel)
			// Skip nested skip-dirs even when git lists them (vendor etc).
			parts := strings.Split(filepath.ToSlash(rel), "/")
			skip := false
			for _, p := range parts[:len(parts)-1] {
				if skipDirs[p] {
					skip = true
					break
				}
			}
			if skip {
				continue
			}
			data, err := os.ReadFile(full)
			if err != nil {
				continue
			}
			if !accept(rel, data) {
				continue
			}
			out <- File{Path: full, Repo: repoName, Data: data}
		}
	}
	return nil
}
